name: CI

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # - name: Install poetry
      #   run: pipx install poetry

      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.10'
      #     cache: 'poetry'

      - name: Python Code Style, Quality, and Lint
        uses: weibullguy/python-lint-plus@v1.8.0
        with:
          python-root-list: 'app tests'
          use-black: true
          use-mypy: false

      # - name: Install python dependencies
      #   run: poetry install --no-interaction --no-root
      
      # - name: Check code quality
      #   run: poetry run black . --check

      # - name: Test with pytest
      #   run: |
      #     poetry run coverage run --rcfile ./pyproject.toml -m pytest ./tests
      #     poetry run coverage report --fail-under 95